// Draw by Numeral
// (c) Brendan Berg 2019-2024

import * as Op from './opcodes';

let currentSymbol = 0;

const gensym = () => {
    return '$_BUILTIN_JS_' + (currentSymbol++).toString(36).toUpperCase();
};

const emitBuiltins = () => {
    const _abs_a = gensym();

    const _line_a = gensym();
    const _line_b = gensym();
    const _line_c = gensym();
    const _line_d = gensym();
    const _line_e = gensym();
    const _line_f = gensym();

    const _plotlow = gensym();
    const _plotlow_a = gensym();
    const _plotlow_b = gensym();
    const _plotlow_c = gensym();
    const _plotlow_d = gensym();
    const _plotlow_e = gensym();
    const _plotlow_f = gensym();
    const _plotlow_g = gensym();

    const _plothigh = gensym();
    const _plothigh_a = gensym();
    const _plothigh_b = gensym();
    const _plothigh_c = gensym();
    const _plothigh_d = gensym();
    const _plothigh_e = gensym();
    const _plothigh_f = gensym();

    const _field_a = gensym();
    const _field_b = gensym();
    const _field_c = gensym();
    const _field_d = gensym();
    const _field_e = gensym();
    const _field_f = gensym();

    return [
        Op.LABEL,
        'abs',
        Op.STACK_ALLOC,
        0,
        Op.DUPLICATE,
        Op.JUMP_IF_NEGATIVE,
        _abs_a,
        Op.STACK_FREE,
        0,
        Op.RETURN,
        Op.LABEL,
        _abs_a,
        Op.NEGATE,
        Op.STACK_FREE,
        0,
        Op.RETURN,
        //	-------------------------------
        Op.LABEL,
        'field',
        Op.STACK_ALLOC,
        2,
        Op.SET_ARGUMENT,
        4,
        Op.SET_ARGUMENT,
        3,
        Op.SET_ARGUMENT,
        2,
        Op.SET_ARGUMENT,
        1,
        Op.SET_ARGUMENT,
        0,
        Op.CONSTANT,
        255,
        Op.GET_ARGUMENT,
        4,
        Op.DUPLICATE,
        Op.JUMP_IF_NEGATIVE,
        _field_a,
        Op.DUPLICATE,
        Op.CONSTANT,
        100,
        Op.SUBTRACT,
        Op.JUMP_IF_NONNEGATIVE,
        _field_b,
        Op.JUMP,
        _field_c,
        Op.LABEL,
        _field_a,
        Op.POP,
        Op.CONSTANT,
        0,
        Op.JUMP,
        _field_c,
        Op.LABEL,
        _field_b,
        Op.POP,
        Op.CONSTANT,
        100,
        Op.LABEL,
        _field_c,
        Op.CONSTANT,
        255,
        Op.MULTIPLY,
        Op.CONSTANT,
        100,
        Op.DIVIDE,
        Op.SUBTRACT,
        Op.PACK_GRAY,
        Op.SET_PEN_COLOR,
        Op.GET_ARGUMENT,
        0,
        Op.DUPLICATE,
        Op.SET_LOCAL,
        0,
        Op.GET_ARGUMENT,
        2,
        Op.DUPLICATE,
        Op.SET_LOCAL,
        1,
        Op.SUBTRACT,
        Op.LABEL,
        _field_d,
        Op.GET_LOCAL,
        0,
        Op.GET_ARGUMENT,
        1,
        Op.GET_LOCAL,
        0,
        Op.GET_ARGUMENT,
        3,
        Op.STACK_ALLOC,
        4,
        Op.CALL,
        'line',
        Op.STACK_FREE,
        4,
        Op.POP,
        Op.DUPLICATE,
        Op.JUMP_IF_NEGATIVE,
        _field_e,
        Op.GET_LOCAL,
        1,
        Op.GET_LOCAL,
        0,
        Op.DUPLICATE,
        Op.CONSTANT,
        1,
        Op.SUBTRACT,
        Op.SET_LOCAL,
        0,
        Op.CONSTANT,
        1,
        Op.ADD,
        Op.SUBTRACT,
        Op.JUMP,
        _field_f,
        Op.LABEL,
        _field_e,
        Op.GET_LOCAL,
        0,
        Op.CONSTANT,
        1,
        Op.ADD,
        Op.DUPLICATE,
        Op.SET_LOCAL,
        0,
        Op.GET_LOCAL,
        1,
        Op.CONSTANT,
        1,
        Op.ADD,
        Op.SUBTRACT,
        Op.LABEL,
        _field_f,
        Op.JUMP_IF_NEGATIVE,
        _field_d,
        Op.POP,
        Op.STACK_FREE,
        2,
        Op.CONSTANT,
        0,
        Op.RETURN,
        //	-------------------------------
        Op.LABEL,
        'line',
        Op.STACK_ALLOC,
        2,
        Op.ARGUMENT,
        'x0',
        Op.ARGUMENT,
        'y0',
        Op.ARGUMENT,
        'x1',
        Op.ARGUMENT,
        'y1',
        Op.SET_ARGUMENT,
        'y1', // 3
        Op.SET_ARGUMENT,
        'x1', // 2
        Op.SET_ARGUMENT,
        'y0', // 1
        Op.SET_ARGUMENT,
        'x0', // 0

        Op.GET_ARGUMENT,
        'y1',
        Op.GET_ARGUMENT,
        'y0',
        Op.SUBTRACT,
        Op.CALL,
        'abs',
        Op.SET_LOCAL,
        'magY', // 0
        Op.GET_ARGUMENT,
        'x1',
        Op.GET_ARGUMENT,
        'x0',
        Op.SUBTRACT,
        Op.CALL,
        'abs',
        Op.SET_LOCAL,
        'magX', // 1

        Op.GET_LOCAL,
        'magX',
        Op.GET_LOCAL,
        'magY',
        Op.SUBTRACT,
        Op.JUMP_IF_NEGATIVE,
        _line_a,

        Op.GET_ARGUMENT,
        'x1',
        Op.GET_ARGUMENT,
        'x0',
        Op.SUBTRACT,
        Op.JUMP_IF_NEGATIVE,
        _line_b,
        Op.GET_ARGUMENT,
        'x0',
        Op.GET_ARGUMENT,
        'y0',
        Op.GET_ARGUMENT,
        'x1',
        Op.GET_ARGUMENT,
        'y1',
        Op.JUMP,
        _line_c,
        Op.LABEL,
        _line_b,
        Op.GET_ARGUMENT,
        'x1',
        Op.GET_ARGUMENT,
        'y1',
        Op.GET_ARGUMENT,
        'x0',
        Op.GET_ARGUMENT,
        'y0',
        Op.LABEL,
        _line_c,
        Op.STACK_ALLOC,
        4,
        Op.CALL,
        _plotlow,
        Op.STACK_FREE,
        4,
        Op.POP,
        Op.JUMP,
        _line_f,

        Op.LABEL,
        _line_a,
        Op.GET_ARGUMENT,
        'y1',
        Op.GET_ARGUMENT,
        'y0',
        Op.SUBTRACT,
        Op.JUMP_IF_NEGATIVE,
        _line_d,
        Op.GET_ARGUMENT,
        'x0',
        Op.GET_ARGUMENT,
        'y0',
        Op.GET_ARGUMENT,
        'x1',
        Op.GET_ARGUMENT,
        'y1',
        Op.JUMP,
        _line_e,
        Op.LABEL,
        _line_d,
        Op.GET_ARGUMENT,
        'x1',
        Op.GET_ARGUMENT,
        'y1',
        Op.GET_ARGUMENT,
        'x0',
        Op.GET_ARGUMENT,
        'y0',
        Op.LABEL,
        _line_e,
        Op.STACK_ALLOC,
        4,
        Op.CALL,
        _plothigh,
        Op.STACK_FREE,
        4,
        Op.POP,

        Op.LABEL,
        _line_f,
        Op.STACK_FREE,
        2,
        Op.CONSTANT,
        0,
        Op.RETURN,
        //	-------------------------------
        Op.LABEL,
        _plotlow,
        Op.STACK_ALLOC,
        7,
        Op.ARGUMENT,
        'x0',
        Op.ARGUMENT,
        'y0',
        Op.ARGUMENT,
        'x1',
        Op.ARGUMENT,
        'y1',
        Op.SET_ARGUMENT,
        'y1',
        Op.SET_ARGUMENT,
        'x1',
        Op.SET_ARGUMENT,
        'y0',
        Op.SET_ARGUMENT,
        'x0',
        Op.GET_ARGUMENT,
        'x1',
        Op.GET_ARGUMENT,
        'x0',
        Op.SUBTRACT,
        Op.SET_LOCAL,
        'dx', // Span of x
        Op.GET_ARGUMENT,
        'y1',
        Op.GET_ARGUMENT,
        'y0',
        Op.SUBTRACT,
        Op.SET_LOCAL,
        'dy', // Span of y
        Op.CONSTANT,
        1,
        Op.SET_LOCAL,
        'yi', // Change in y
        Op.GET_LOCAL,
        'dy',
        Op.CONSTANT,
        0,
        Op.SUBTRACT,
        Op.JUMP_IF_NONNEGATIVE,
        _plotlow_a, // Compare dY - 0 > 0
        Op.CONSTANT,
        -1,
        Op.SET_LOCAL,
        'yi',
        Op.CONSTANT,
        0,
        Op.GET_LOCAL,
        'dy',
        Op.SUBTRACT,
        Op.SET_LOCAL,
        'dy',
        Op.LABEL,
        _plotlow_a, // dY - 0
        Op.CONSTANT,
        2,
        Op.GET_LOCAL,
        'dy',
        Op.MULTIPLY,
        Op.GET_LOCAL,
        'dx',
        Op.SUBTRACT,
        Op.SET_LOCAL,
        'd',
        Op.GET_ARGUMENT,
        'y0',
        Op.SET_LOCAL,
        'y',
        Op.GET_ARGUMENT,
        'x0',
        Op.DUPLICATE,
        Op.SET_LOCAL,
        'x', // leaves x0 on the stack
        Op.GET_ARGUMENT,
        'x1',
        Op.DUPLICATE,
        Op.SET_LOCAL,
        _plotlow_f, // leaves x1 on the stack
        Op.SUBTRACT, // leaves x1 - x0 on the stack
        Op.LABEL,
        _plotlow_b,
        Op.GET_LOCAL,
        'x',
        Op.GET_LOCAL,
        'y',
        Op.FILL_PIXEL,
        Op.CONSTANT,
        0,
        Op.GET_LOCAL,
        'd',
        Op.SUBTRACT,
        Op.JUMP_IF_NONNEGATIVE,
        _plotlow_c,
        Op.GET_LOCAL,
        'y',
        Op.GET_LOCAL,
        'yi',
        Op.ADD,
        Op.SET_LOCAL,
        'y', // y = y + yi
        Op.GET_LOCAL,
        'd',
        Op.CONSTANT,
        2,
        Op.GET_LOCAL,
        'dx',
        Op.MULTIPLY,
        Op.SUBTRACT,
        Op.SET_LOCAL,
        'd', // d = d - 2 * dx
        Op.LABEL,
        _plotlow_c,
        Op.GET_LOCAL,
        'd',
        Op.CONSTANT,
        2,
        Op.GET_LOCAL,
        'dy',
        Op.MULTIPLY,
        Op.ADD,
        Op.SET_LOCAL,
        'd', // d = d + 2 * dy
        Op.DUPLICATE,
        Op.JUMP_IF_ZERO,
        _plotlow_g,
        Op.DUPLICATE,
        Op.JUMP_IF_NEGATIVE,
        _plotlow_d,
        Op.GET_LOCAL,
        _plotlow_f,
        Op.GET_LOCAL,
        'x',
        Op.DUPLICATE,
        Op.CONSTANT,
        1,
        Op.SUBTRACT,
        Op.SET_LOCAL,
        'x',
        Op.CONSTANT,
        1,
        Op.ADD,
        Op.SUBTRACT,
        Op.JUMP,
        _plotlow_e,
        Op.LABEL,
        _plotlow_d,
        Op.GET_LOCAL,
        'x',
        Op.CONSTANT,
        1,
        Op.ADD,
        Op.DUPLICATE,
        Op.SET_LOCAL,
        'x',
        Op.GET_LOCAL,
        _plotlow_f,
        Op.CONSTANT,
        1,
        Op.ADD,
        Op.SUBTRACT,
        Op.LABEL,
        _plotlow_e,
        Op.JUMP_IF_NEGATIVE,
        _plotlow_b,
        Op.LABEL,
        _plotlow_g,
        Op.POP,
        Op.STACK_FREE,
        7,
        Op.CONSTANT,
        0,
        Op.RETURN,
        //	-------------------------------
        Op.LABEL,
        _plothigh,
        Op.STACK_ALLOC,
        7,
        Op.ARGUMENT,
        'x0',
        Op.ARGUMENT,
        'y0',
        Op.ARGUMENT,
        'x1',
        Op.ARGUMENT,
        'y1',
        Op.SET_ARGUMENT,
        'y1',
        Op.SET_ARGUMENT,
        'x1',
        Op.SET_ARGUMENT,
        'y0',
        Op.SET_ARGUMENT,
        'x0',
        Op.GET_ARGUMENT,
        'x1',
        Op.GET_ARGUMENT,
        'x0',
        Op.SUBTRACT,
        Op.SET_LOCAL,
        'dx',
        Op.GET_ARGUMENT,
        'y1',
        Op.GET_ARGUMENT,
        'y0',
        Op.SUBTRACT,
        Op.SET_LOCAL,
        'dy',
        Op.CONSTANT,
        1,
        Op.SET_LOCAL,
        'xi',
        Op.GET_LOCAL,
        'dx',
        Op.CONSTANT,
        0,
        Op.SUBTRACT,
        Op.JUMP_IF_NONNEGATIVE,
        _plothigh_a,
        Op.CONSTANT,
        -1,
        Op.SET_LOCAL,
        'xi',
        Op.CONSTANT,
        0,
        Op.GET_LOCAL,
        'dx',
        Op.SUBTRACT,
        Op.SET_LOCAL,
        'dx',
        Op.LABEL,
        _plothigh_a,
        Op.CONSTANT,
        2,
        Op.GET_LOCAL,
        'dx',
        Op.MULTIPLY,
        Op.GET_LOCAL,
        'dy',
        Op.SUBTRACT,
        Op.SET_LOCAL,
        'd',
        Op.GET_ARGUMENT,
        'x0',
        Op.SET_LOCAL,
        'x',
        Op.GET_ARGUMENT,
        'y0',
        Op.DUPLICATE,
        Op.SET_LOCAL,
        'y',
        Op.GET_ARGUMENT,
        'y1',
        Op.DUPLICATE,
        Op.SET_LOCAL,
        _plothigh_f,
        Op.SUBTRACT,
        Op.LABEL,
        _plothigh_b,
        Op.GET_LOCAL,
        'x',
        Op.GET_LOCAL,
        'y',
        Op.FILL_PIXEL,
        Op.CONSTANT,
        0,
        Op.GET_LOCAL,
        'd',
        Op.SUBTRACT,
        Op.JUMP_IF_NONNEGATIVE,
        _plothigh_c,
        Op.GET_LOCAL,
        'x',
        Op.GET_LOCAL,
        'xi',
        Op.ADD,
        Op.SET_LOCAL,
        'x',
        Op.GET_LOCAL,
        'd',
        Op.CONSTANT,
        2,
        Op.GET_LOCAL,
        'dy',
        Op.MULTIPLY,
        Op.SUBTRACT,
        Op.SET_LOCAL,
        'd',
        Op.LABEL,
        _plothigh_c,
        Op.GET_LOCAL,
        'd',
        Op.CONSTANT,
        2,
        Op.GET_LOCAL,
        'dx',
        Op.MULTIPLY,
        Op.ADD,
        Op.SET_LOCAL,
        'd',
        Op.DUPLICATE,
        Op.JUMP_IF_NEGATIVE,
        _plothigh_d,
        Op.GET_LOCAL,
        _plothigh_f,
        Op.GET_LOCAL,
        'y',
        Op.DUPLICATE,
        Op.CONSTANT,
        1,
        Op.SUBTRACT,
        Op.SET_LOCAL,
        'y',
        Op.CONSTANT,
        1,
        Op.ADD,
        Op.SUBTRACT,
        Op.JUMP,
        _plothigh_e,
        Op.LABEL,
        _plothigh_d,
        Op.GET_LOCAL,
        'y',
        Op.CONSTANT,
        1,
        Op.ADD,
        Op.DUPLICATE,
        Op.SET_LOCAL,
        'y',
        Op.GET_LOCAL,
        _plothigh_f,
        Op.CONSTANT,
        1,
        Op.ADD,
        Op.SUBTRACT,
        Op.LABEL,
        _plothigh_e,
        Op.JUMP_IF_NEGATIVE,
        _plothigh_b,
        Op.POP,
        Op.STACK_FREE,
        7,
        Op.CONSTANT,
        0,
        Op.RETURN,
    ];
};

export default emitBuiltins;
